const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT_DIR, 'src');
const ELECTRON_DIR = path.join(ROOT_DIR, 'electron');
const OUTPUT_FILE = path.join(ROOT_DIR, 'DEPENDENCY_GRAPH.md');

// Helper to recursively get files
function getFiles(dir, fileList = []) {
  if (!fs.existsSync(dir)) return fileList;
  const files = fs.readdirSync(dir);
  files.forEach(file => {
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      if (file !== 'node_modules' && file !== 'dist' && file !== 'dist-electron' && file !== '.git') {
        getFiles(filePath, fileList);
      }
    } else {
      if (file.endsWith('.ts') || file.endsWith('.tsx')) {
        fileList.push(filePath);
      }
    }
  });
  return fileList;
}

function generateGraph() {
  const allFiles = [...getFiles(SRC_DIR), ...getFiles(ELECTRON_DIR)];
  const relativeFilePaths = allFiles.map(f => path.relative(ROOT_DIR, f).replace(/\\/g, '/'));
  
  const fileNodes = {};
  const importEdges = [];
  const ipcEvents = { send: [], receive: [], handle: [] };

  // Regex definitions
  const importRegex = /import\s+(?:[^\n]+?\s+from\s+)?['"](\.\/.*?|\.\.\/.*?)['"]/g;
  const ipcSendRegex = /(?:ipcRenderer\.send|ipcRenderer\.invoke)\(['"]([^'"]+)['"]/g;
  const ipcOnRegex = /(?:ipcRenderer\.on|ipcMain\.on)\(['"]([^'"]+)['"]/g;
  const ipcHandleRegex = /ipcMain\.handle\(['"]([^'"]+)['"]/g;

  allFiles.forEach((filePath, idx) => {
    const relativePath = relativeFilePaths[idx];
    const fileName = path.basename(relativePath);
    const nodeName = relativePath.replace(/[^a-zA-Z0-9]/g, '_');
    
    fileNodes[nodeName] = {
      label: relativePath,
      name: fileName,
      type: relativePath.startsWith('electron/') ? 'main' : 'renderer'
    };

    const content = fs.readFileSync(filePath, 'utf8');

    // Parse Imports
    let match;
    while ((match = importRegex.exec(content)) !== null) {
      const importedPath = match[1];
      const absoluteImported = path.resolve(path.dirname(filePath), importedPath);
      
      // Resolve extension (ts, tsx, js, etc)
      let resolvedRelative = null;
      const extensions = ['.ts', '.tsx', '/index.ts', '/index.tsx', '.d.ts'];
      for (const ext of extensions) {
        let checkPath = absoluteImported + ext;
        if (ext.startsWith('/index')) {
          checkPath = path.join(absoluteImported, ext.split('/')[1]);
        }
        if (fs.existsSync(checkPath) && !fs.statSync(checkPath).isDirectory()) {
          resolvedRelative = path.relative(ROOT_DIR, checkPath).replace(/\\/g, '/');
          break;
        }
      }

      if (resolvedRelative) {
        const importedNodeName = resolvedRelative.replace(/[^a-zA-Z0-9]/g, '_');
        importEdges.push({ from: nodeName, to: importedNodeName });
      }
    }

    // Parse IPC Send
    while ((match = ipcSendRegex.exec(content)) !== null) {
      ipcEvents.send.push({ file: nodeName, event: match[1] });
    }
    // Parse IPC On
    while ((match = ipcOnRegex.exec(content)) !== null) {
      ipcEvents.receive.push({ file: nodeName, event: match[1] });
    }
    // Parse IPC Handle
    while ((match = ipcHandleRegex.exec(content)) !== null) {
      ipcEvents.handle.push({ file: nodeName, event: match[1] });
    }
  });

  // Generate Mermaid output
  let mermaid = '```mermaid\nflowchart TD\n';
  
  // Style definitions
  mermaid += '    classDef main fill:#f96,stroke:#333,stroke-width:2px,color:#000;\n';
  mermaid += '    classDef renderer fill:#6cf,stroke:#333,stroke-width:1px,color:#000;\n\n';

  // Nodes
  mermaid += '    %% File Nodes\n';
  Object.keys(fileNodes).forEach(nodeName => {
    const node = fileNodes[nodeName];
    mermaid += `    ${nodeName}["${node.label}"]\n`;
    mermaid += `    class ${nodeName} ${node.type};\n`;
  });

  // Import Edges
  mermaid += '\n    %% Import Dependencies\n';
  importEdges.forEach(edge => {
    mermaid += `    ${edge.from} --> ${edge.to}\n`;
  });

  // IPC Communications
  mermaid += '\n    %% IPC Event Flows\n';
  const ipcConnections = [];
  ipcEvents.send.forEach(send => {
    // Find matching handle/receive
    const targets = [
      ...ipcEvents.handle.filter(h => h.event === send.event),
      ...ipcEvents.receive.filter(r => r.event === send.event && r.file !== send.file)
    ];
    targets.forEach(target => {
      ipcConnections.push({
        from: send.file,
        to: target.file,
        label: `ipc: ${send.event}`
      });
    });
  });

  ipcConnections.forEach(conn => {
    mermaid += `    ${conn.from} == "${conn.label}" ==> ${conn.to}\n`;
  });

  mermaid += '```\n';

  // Build markdown file content
  const mdContent = `# SideBrowser Dependency & IPC Communication Graph

This file is automatically generated by running \`npm run graphify\`. It illustrates the internal module imports and inter-process IPC communication channels.

- **Orange Nodes:** Electron Main Process scripts
- **Blue Nodes:** React Renderer frontend components
- **Double Thick Lines (==):** IPC Event-driven messaging

${mermaid}
`;

  fs.writeFileSync(OUTPUT_FILE, mdContent, 'utf8');
  console.log(`Successfully generated dependency graph at: ${OUTPUT_FILE}`);
}

generateGraph();
