name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest
    

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build and Package
        run: |
          npm run build
          npm run rebuild
          npx electron-builder -p never

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*/*.exe
            release/*/*.blockmap
            release/*/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
